version: '2.3'

services:
  carla-server:
    build: ./server/
    ports:
        - 2000-2002:2000-2002
    image: carla-server
    runtime: nvidia
    command: ./CarlaUE4.sh /Game/Maps/Town01 -carla-server -benchmark -fps=15 -windowed -ResX=800 -ResY=600

  carla-client:
    build: ./client/
    network_mode: 'host'
    volumes:
        - .:/app
    runtime: nvidia
    image: carla-client
    depends_on:
        - carla-server

  nvsmi:
      image: ubuntu:18.04
      runtime: nvidia
      environment:
          - NVIDIA_VISIBLE_DEVICES=all
      command: nvidia-smi
